### ISSUE TITLE
Restraint logs are overwritten when resuming.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/brer_plugin#14]
The "convergence" and "production" phases of the BRER workflow are intended to be compatible with GROMACS continuation-from-checkpoint, for simulations managed by [run-brer](https://github.com/kassonlab/run_brer).

However, the log files in which the LinearStopRestraint and LinearRestraint (the plugin potentials used for the convergence and production phases, respectively) are opened with mode "w" instead of mode "a".

This means that trajectories that are interrupted (such as for HPC job walltime limits) may be successfully completed with subsequent jobs, but the data logged to these files would be overwritten.

Two options:
* run_brer could rotate the log files, backing up existing log files before launching simulations
* brer_plugin could open log files with "append" mode (`a`) instead of truncated write mode (`w`). (Note that log lines are flushed immediately each time they are written, so the chance of file corruption should be very low.)

I don't think that `run_brer` currently officially knows about these files, so the latter option would seem cleaner.

**Comment by eirrgang** [comment]
Ref https://github.com/kassonlab/brer_plugin/blob/de87b7d3bb6c0a296b878ae98aa315f6a88198d6/src/cpp/linearstoppotential.cpp#L64 and https://github.com/kassonlab/brer_plugin/blob/de87b7d3bb6c0a296b878ae98aa315f6a88198d6/src/cpp/linearpotential.cpp#L50

**Comment by eirrgang** [comment]
Technically, `run_brer` generates the log filename at https://github.com/kassonlab/run_brer/blob/72333e76749c7f62c36625328a6c2cd202e468d7/run_brer/run_data.py#L83

But it looks like it doesn't retain knowledge of this file for any reason other than to provide it as a parameter when instantiating the BRER potential.

**Comment by carolinedav** [comment]
If we append with "a", the ensemble would restart, but the logs would show a complete history of all runs, correct?

**Comment by carolinedav** [comment]
Could we work in a statement in the log file (or perhaps a `break`) that notes a restart (in theory, the restart would show with the change of time, but I don't know if we want something more "official")?

**Comment by eirrgang** [comment]
> If we append with "a", the ensemble would restart, but the logs would show a complete history of all runs, correct?

Correct. Well, specifically, the log file that looks like "residueA-residueB" and has 4 columns with time, R, target, and alpha value.

I don't think we want to mess up the convenient array layout of the file with an annotation of interruption. The interruption should be evident from the other log and output files.

There may be a chance that a line could be repeated after a restart if the simulation is interrupted on a step that produces a log line, but I didn't check the logic that carefully... Fortunately, it is pretty easy to accept only the last line in monotonic data keyed by the first column. I think numpy has a kwarg for it, but you can also just do `sort -u`.
